// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: test.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumType int32

const (
	EnumType_TEST    EnumType = 0
	EnumType_ANOTHER EnumType = 1
)

// Enum value maps for EnumType.
var (
	EnumType_name = map[int32]string{
		0: "TEST",
		1: "ANOTHER",
	}
	EnumType_value = map[string]int32{
		"TEST":    0,
		"ANOTHER": 1,
	}
)

func (x EnumType) Enum() *EnumType {
	p := new(EnumType)
	*p = x
	return p
}

func (x EnumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (EnumType) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x EnumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumType.Descriptor instead.
func (EnumType) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field *Embed `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	// Types that are assignable to Variant:
	//	*Msg_A
	//	*Msg_B
	//	*Msg_C
	Variant  isMsg_Variant       `protobuf_oneof:"Variant"`
	MapField map[string]*Embed   `protobuf:"bytes,15,rep,name=MapField,proto3" json:"MapField,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RepField []*Embed            `protobuf:"bytes,20,rep,name=RepField,proto3" json:"RepField,omitempty"`
	En       EnumType            `protobuf:"varint,25,opt,name=En,proto3,enum=test.EnumType" json:"En,omitempty"`
	RepEnum  []EnumType          `protobuf:"varint,30,rep,packed,name=RepEnum,proto3,enum=test.EnumType" json:"RepEnum,omitempty"`
	MapEnum  map[uint32]EnumType `protobuf:"bytes,50,rep,name=MapEnum,proto3" json:"MapEnum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=test.EnumType"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetField() *Embed {
	if x != nil {
		return x.Field
	}
	return nil
}

func (m *Msg) GetVariant() isMsg_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *Msg) GetA() string {
	if x, ok := x.GetVariant().(*Msg_A); ok {
		return x.A
	}
	return ""
}

func (x *Msg) GetB() string {
	if x, ok := x.GetVariant().(*Msg_B); ok {
		return x.B
	}
	return ""
}

func (x *Msg) GetC() *Embed {
	if x, ok := x.GetVariant().(*Msg_C); ok {
		return x.C
	}
	return nil
}

func (x *Msg) GetMapField() map[string]*Embed {
	if x != nil {
		return x.MapField
	}
	return nil
}

func (x *Msg) GetRepField() []*Embed {
	if x != nil {
		return x.RepField
	}
	return nil
}

func (x *Msg) GetEn() EnumType {
	if x != nil {
		return x.En
	}
	return EnumType_TEST
}

func (x *Msg) GetRepEnum() []EnumType {
	if x != nil {
		return x.RepEnum
	}
	return nil
}

func (x *Msg) GetMapEnum() map[uint32]EnumType {
	if x != nil {
		return x.MapEnum
	}
	return nil
}

type isMsg_Variant interface {
	isMsg_Variant()
}

type Msg_A struct {
	A string `protobuf:"bytes,2,opt,name=A,proto3,oneof"`
}

type Msg_B struct {
	B string `protobuf:"bytes,3,opt,name=B,proto3,oneof"`
}

type Msg_C struct {
	C *Embed `protobuf:"bytes,4,opt,name=C,proto3,oneof"`
}

func (*Msg_A) isMsg_Variant() {}

func (*Msg_B) isMsg_Variant() {}

func (*Msg_C) isMsg_Variant() {}

type Embed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *Embed) Reset() {
	*x = Embed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Embed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embed) ProtoMessage() {}

func (x *Embed) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embed.ProtoReflect.Descriptor instead.
func (*Embed) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *Embed) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65,
	0x73, 0x74, 0x22, 0xe0, 0x03, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x05, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x0e, 0x0a,
	0x01, 0x41, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x41, 0x12, 0x0e, 0x0a,
	0x01, 0x42, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x42, 0x12, 0x1b, 0x0a,
	0x01, 0x43, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x45, 0x6d, 0x62, 0x65, 0x64, 0x48, 0x00, 0x52, 0x01, 0x43, 0x12, 0x33, 0x0a, 0x08, 0x4d, 0x61,
	0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x27, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x14, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x08,
	0x52, 0x65, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x02, 0x45, 0x6e, 0x18, 0x19,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x45, 0x6e, 0x12, 0x28, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x45,
	0x6e, 0x75, 0x6d, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x52, 0x65, 0x70, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x30, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x75, 0x6d, 0x18, 0x32, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x75, 0x6d, 0x1a, 0x48, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x4a,
	0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x22, 0x1b, 0x0a, 0x05, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65,
	0x78, 0x74, 0x2a, 0x21, 0x0a, 0x08, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x54, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x4f, 0x54,
	0x48, 0x45, 0x52, 0x10, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x64, 0x6d, 0x72, 0x63, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_proto_goTypes = []interface{}{
	(EnumType)(0), // 0: test.EnumType
	(*Msg)(nil),   // 1: test.Msg
	(*Embed)(nil), // 2: test.Embed
	nil,           // 3: test.Msg.MapFieldEntry
	nil,           // 4: test.Msg.MapEnumEntry
}
var file_test_proto_depIdxs = []int32{
	2, // 0: test.Msg.Field:type_name -> test.Embed
	2, // 1: test.Msg.C:type_name -> test.Embed
	3, // 2: test.Msg.MapField:type_name -> test.Msg.MapFieldEntry
	2, // 3: test.Msg.RepField:type_name -> test.Embed
	0, // 4: test.Msg.En:type_name -> test.EnumType
	0, // 5: test.Msg.RepEnum:type_name -> test.EnumType
	4, // 6: test.Msg.MapEnum:type_name -> test.Msg.MapEnumEntry
	2, // 7: test.Msg.MapFieldEntry.value:type_name -> test.Embed
	0, // 8: test.Msg.MapEnumEntry.value:type_name -> test.EnumType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Embed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_test_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Msg_A)(nil),
		(*Msg_B)(nil),
		(*Msg_C)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
